language: generic

services:
  - docker

script:
  - docker --version

  # build images
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend

  # Add tags to images
  - docker tag udagram-api-feed "$DOCKER_USERNAME/udagram-api-feed:latest"
  - docker tag udagram-api-user "$DOCKER_USERNAME/udagram-api-user:latest"
  - docker tag reverseproxy "$DOCKER_USERNAME/reverseproxy:latest"
  - docker tag udagram-frontend "$DOCKER_USERNAME/udagram-frontend:latest"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # push images
  - docker push "$DOCKER_USERNAME/udagram-api-feed:latest"
  - docker push "$DOCKER_USERNAME/udagram-api-user:latest"
  - docker push "$DOCKER_USERNAME/reverseproxy:latest"
  - docker push "$DOCKER_USERNAME/udagram-frontend:latest"